/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Cards: typeof import('./src/components/homeView/cards.vue')['default']
    CardsBooks: typeof import('./src/components/bookView/cardsBooks.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Charts: typeof import('./src/components/homeView/charts.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DynamicPhotoFrame: typeof import('./src/components/DynamicPhotoFrame.vue')['default']
    EditPopover: typeof import('./src/components/bookView/editPopover.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Knob: typeof import('primevue/knob')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuComponent: typeof import('./src/components/MenuComponent.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/bookView/searchBar.vue')['default']
    Select: typeof import('primevue/select')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    SpeedDialMenu: typeof import('./src/components/bookView/speedDialMenu.vue')['default']
    Tables: typeof import('./src/components/homeView/tables.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    UsersTable: typeof import('./src/components/usersView/usersTable.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
